include ~/.cache/by-mgr/hellwal/color-kitty.conf

# 设置字体
 font_family      JetBrains Mono
 bold_font        auto
 italic_font      auto
 bold_italic_font auto

# 设置字体大小
  font_size 14

# 2. 扩展中文字体（精准接管汉字区）
# --- 扩展更纱黑体 (解决锐利感，确保对齐) ---
# U+4E00-U+9FFF: 常用汉字
# U+3400-U+4DBF: 扩展区 A
# 这里选用了 SemiBold (半粗体)，它比 Regular 厚实，比 Bold 细致，视觉非常温润
symbol_map U+4E00-U+9FFF,U+3400-U+4DBF Sarasa Term SC SemiBold
# github主页：https://github.com/be5invis/Sarasa-Gothic

# 思源黑体
# 需要安装 google-noto-sans-cjk-fonts google-noto-serif-cjk-fonts 字体包
# symbol_map U+4E00-U+9FFF,U+3400-U+4DBF Noto Sans CJK SC Medium
  
  #设置光标

  #设置光标形状
  curcursor_shape block
  text_fg_override_threshold 0

# 设置光标

  #未聚焦光标形状
  cursor_shape_unfocused block
  #未聚焦光标停止闪烁时间，0为永不闪烁
  cursor_stop_blinking_after 0

  #光标追踪动画,0为禁用，大于0的任何值将启用
  cursor_trail 1
  #设置启用光标路径的距离阈值
  cursor_trail_start_threshold 2
  #设置光标追踪的颜色
  cursor_trail_color none

# 背景设置
  foreground #dddddd
  background #000000
  #背景透明度,介于0至1之间
  background_opacity 0.6
  #背景模糊，正值启用
  background_blur 2
  #背景图片
  background_image none

# 窗口

  #隐藏标题栏
  hide_window_decorations yes
  window_padding_width 10

# 允许 Kitty 接收外部指令，实现瞬间热重载
allow_remote_control yes
listen_on unix:/tmp/kitty
